server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/bignet?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=CTT


#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bignet.db.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

netty:
  port: 8081